### ISSUE TITLE
error views not working when placed in the theme

### ISSUE THREAD

**Issue by nermamax** [igaster/laravel-theme#47] opened 2017-03-08 11:49 UTC
Here is my code:
`
$post = Post::where('slug', $slug)->firstOrFail();
`
If I look for non existing post and have my error views placed inside theme/errors
404.blade.php
403.blade.php
503.blade.php

they are not found by laravel when looking for non existing model.

If I however place the errors folder on same level as the theme folder then laravel finds them and renders them instead of standar laravel "NotFoundHttpException in Handler.php line 131:" message it shows if there are no error views

Is it possible to use them inside the themes folder?

**Comment by igaster** [comment] 2017-03-08 12:17
When are you setting your active theme? Can you confirm that the current Theme has been set before the NotFoundHttpException is thrown?

For example place:
```
dd(\Theme::get());
```
bofore your code to display current theme...

If everything seems OK, you can post your theme.php config file to inspect..

**Comment by nermamax** [comment] 2017-03-08 12:30
that code above printed the name of my theme which I had set as active in the theme.php and here is my theme.php file:



`


	/*
	|--------------------------------------------------------------------------
	| Switch this package on/off. Usefull for testing...
	|--------------------------------------------------------------------------
	*/

	'enabled' => true,

    /*
    |--------------------------------------------------------------------------
    | File path where themes will be located.
    | Can be outside default views path EG: resources/themes
    | Leave it null if you place your themes in the default views folder 
    | (as defined in config\views.php)
    |--------------------------------------------------------------------------
    */

    'themes_path' => null, // eg: realpath(base_path('resources/themes'))

	/*
	|--------------------------------------------------------------------------
	| Set behavior if an asset is not found in a Theme hierarcy.
	| Available options: THROW_EXCEPTION | LOG_ERROR | ASSUME_EXISTS | IGNORE
	|--------------------------------------------------------------------------
	*/

	'asset_not_found' => 'LOG_ERROR',

	/*
	|--------------------------------------------------------------------------
	| Set the Active Theme. Can be set at runtime with:
	|  Themes::set('theme-name');
	|--------------------------------------------------------------------------
	*/

	'active' => 'larapress_2017',

	/*
	|--------------------------------------------------------------------------
	| Define available themes. Format:
	|
	| 	'theme-name' => [
	| 		'extends'	 	=> 'theme-to-extend',  // optional
	| 		'views-path' 	=> 'path-to-views',    // defaults to: resources/views/theme-name
	| 		'asset-path' 	=> 'path-to-assets',   // defaults to: public/theme-name
	|
	|		// you can add your own custom keys and retrieve them with Theme::config('key');
	| 		'key' 			=> 'value', 
	| 	],
	|
	|--------------------------------------------------------------------------
	*/

	'themes' => [

        'larapress_2017' => [
            'extends'	 	=> null,
            'views-path' 	=> 'larapress_2017',
            'asset-path' 	=> 'themes/larapress_2017',
        ],

		// Add your themes here...

		/*--------------[ Example Structre ]-------------

			// Recomended (all defaults) : Assets -> \public\BasicTheme , Views -> \resources\views\BasicTheme

			'BasicTheme',


			// This theme shares the views with BasicTheme but defines its own assets in \public\SomeTheme

			'SomeTheme' => [
				'views-path'	=> 'BasicTheme',
			],


			// This theme extends BasicTheme and ovverides SOME views\assets in its folders

			'AnotherTheme' => [
				'extends'	=> 'BasicTheme',
			],

		------------------------------------------------*/
	],

];
`

**Comment by igaster** [comment] 2017-03-08 12:38
Everything seems fine... I will try to replicate the problem and reply back.

Just for a confirmation, in your setup the following view:

`resources/views/larapress_2017/errors/404.blade.php`

doesn't ovveride the view:

`resources/views/errors/404.blade.php`

when an `NotFoundHttpException` is thrown.

**Comment by nermamax** [comment] 2017-03-08 12:41
That is correct I think, I have not placed 2 errors folders inside themes and on same level as it. I first created my errors folder inside my theme and then when Laravel could not find them I moved them on same level as theme folder and Laravel found them directly. I hope you can fix this since I want themes to be able to customize the errors files.

**Comment by nermamax** [comment] 2017-03-08 14:51
Any luck so far?

I also found another problem when using auth views that laravel genereated when running artisan make:auth If I use move these views to the theme folder they are not found: 

InvalidArgumentException in FileViewFinder.php line 137: View [auth.login] not found.

If I keep these auth views on the same level as theme folder then I get another message:
ErrorException in FileViewFinder.php line 137: View [layouts.app] not found. (View: C:\xampp\htdocs\larapress\resources\views\auth\login.blade.php)

So I need to have them in the themes folder so they can access layouts.app view

Not sure if it matters I am using Laravel 5.4

**Comment by nermamax** [comment] 2017-03-08 15:27
Ok I got auth folder figured out, I just needed to include it like this:

```
Route::group(['middleware'=>'setTheme:Larapress_2017_Theme'], function () {
    Auth::routes();
```

it was outside of that and since theme is not set it could not find the view. By the way I did not explicitly set theme using 'setTheme:Larapress_2017_Theme' middleware but I did set the theme in the themes.php like

'active' => 'Larapress_2017_Theme' which means that even if Auth:routes() was outside of middleware where I set the theme it should have been able to find the views since theme was activated inside themes.php

Could this be a bug?

**Comment by nermamax** [comment] 2017-03-09 19:10
I have found a solution for this, not sure how this could be integrated into your package, perhaps you could figure a way.

Here is what needs to be done:

Inside Exceptions\Handler.php render function needs to be updated like this:

` 
public function render($request, Exception $exception)
{
        $exception = FlattenException::create($exception);
        $statusCode = $exception->getStatusCode($exception);

        if ($statusCode === 404 or $statusCode === 500 or $statusCode === 400 or $statusCode === 401 or $statusCode === 403 or $statusCode === 405 or $statusCode === 408 or $statusCode === 503 and app()->environment() == 'production'){
            return response()->view(Theme::get().'/errors/'.$statusCode, [], $statusCode);
        }
        else{
            return parent::render($request, $exception);
        }

        // return parent::render($request, $exception);
}
`

and error views placed inside theme folder will be found. 

Do you have an idea how to fix this in your package so this does not need to be done?

**Comment by nermamax** [comment] 2017-03-09 19:49
a little update

```
public function render($request, Exception $e)
{
	$exception = FlattenException::create($e);
	$statusCode = $exception->getStatusCode($exception);

	if ($statusCode === 404 or $statusCode === 500 or $statusCode === 400 or $statusCode === 401 or $statusCode === 403 or $statusCode === 405 or $statusCode === 408 or $statusCode === 503 and app()->environment() == 'production'){
		return response()->view(Theme::get().'/errors/'.$statusCode, ['exception' => $e], $statusCode);
	}
	else{
		return parent::render($request, $exception);
	}

	// return parent::render($request, $exception);
}
```

changed the` Exception $exception` to `Exception $e` and added `['exception' => $e]` so that any error message that user puts into abort(404, $message) is sent to the view, because according to laravel docs:

> The abort helper will immediately raise an exception which will be rendered by the exception handler. Optionally, you may provide the response text:
> 
> abort(403, 'Unauthorized action.');

**Comment by igaster** [comment] 2017-03-09 20:32
Hello! I've confirmed the issue in my setup too... Your solution patches the problem but I will need to research into Laravel core to find the reason for that behavior (maybe somewhere is hardcoded?). I will leave this issue open until I've reached better...

Thanks for reporting!

**Comment by nermamax** [comment] 2017-03-09 20:37
Also I found a strange bug with my solution, when not using my solution Laravel 5.4 will give 404 error when the model is not found BUT when using my solution Laravel will actually produce 500 error inside render function. Not sure why it does it, it should give 404, so this solution even if it works it's gives wrong error code if we leave it to Laravel. If we want 404 when model is not found then we'd have to use abort(404) function.

**Comment by nermamax** [comment] 2017-03-10 12:39
updated solution that deals better with 404 and also checks for 401, hope it can help you with your solution

    public function render($request, Exception $e)
    {
        if(app()->environment() != 'production') {
            return parent::render($request, $e);
        }

        if ($e instanceof TokenMismatchException) {
            if ($request->ajax()){
                return response('Token Mismatch Exception', 401);
            }

            return redirect()->route('login');
        }
        
        if ($e instanceof ModelNotFoundException) {
            return response()->view(Theme::get().'.errors.404', ['e' => $e] , 404);
        }

        if ($this->isHttpException($e))
        {
            if( ! \Auth::check() ){
                return redirect()->route('login');
            }

            $exception = FlattenException::create($e);
            $statusCode = $exception->getStatusCode($exception);
            
            if (in_array($statusCode, array(403, 404, 500, 503))){
                if (View::exists(Theme::get().'/errors/'.$statusCode)){
                 return response()->view(Theme::get().'/errors/'.$statusCode, ['e' => $e] , $statusCode);
                } 
            }
        }

        return parent::render($request, $e);
    }

**Comment by igaster** [comment] 2017-03-30 12:00
Fixed in v1.1.4

Thank you for your contribution! It really helped!

**Closed by igaster** 2017-03-30 12:00 UTC

**Comment by nermamax** [comment] 2017-03-30 12:08
Great Igaster, I am glad to have helped. Would you like to share any details what you had to do to fix it?

**Comment by nermamax** [comment] 2017-03-30 12:14
Just had a look, you added replaceNamespace and setupErrorViews, real simple code there :)

**Comment by igaster** [comment] 2017-03-30 19:11
Actually I overriden replaceNamespace() from [Illuminate/View/FileViewFinder.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/View/FileViewFinder.php#L218). Error paths were actually hardcoded at [Illuminate/Foundation/Exceptions/Handler.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L185) and this was the only way to inject theme paths...
